@startuml
' UC004 "Upgrade component - with deleted publishedNotifications" scenario
actor Operations
entity Component
participant ComponentOperator
entity PublishedNotification
participant EventPublishingEnablementOperator
participant "Event Manager" as TMFC019
Component <- Operations : Install
Component -> ComponentOperator: on.update
group For each publishedNotification
ComponentOperator -> PublishedNotification: delete
note right
    A separate publishedNotification resource is created
    for each published notification in the core function,
    security and management sections
end note
    PublishedNotification -> EventPublishingEnablementOperator: on.delete
    EventPublishingEnablementOperator -> TMFC019: delete Hub
    EventPublishingEnablementOperator <-- TMFC019: removed
    PublishedNotification <- EventPublishingEnablementOperator: update
    ComponentOperator <- PublishedNotification: on.update
end
Component <- ComponentOperator: update
@enduml
